### ISSUE TITLE
Merge final robot code into main

### ISSUE THREAD

**Issue by brennan-macaig** [FRC-1721/1721-DeepSpace#7]
This is an issue to mark the progress of branch structure.

Overall, the repository has a confusing branch structure. At this point there should be basically 3 branches - stable (master), bleeding edge (development), and the old kitbot vision testbed.

Stable (master) should be used for the code that gets put on the robot for a competition. This code works, and makes sense logically to read.

Bleeding edge is for tuning, working on new features, or testing subsystems that are untested (climber anyone?).

**Comment by TR45HM4N1721** [comment]
That's what we're doing. It looks a little odd at the moment, but that's just because all the lift work is untested, as is the intake. If we had tangible subsystems, we'd be working in master.
